name: 'Destroy Nginx Deployment'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Are you sure you want to destroy the Nginx deployment?'
        required: true
        default: 'no'

jobs:
  destroy:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    name: 'Destroy Nginx Deployment'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Set up Google Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Install gke-gcloud-auth-plugin'
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-cli
        gcloud components install gke-gcloud-auth-plugin

    - name: 'Authenticate to Google Cloud'
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > /home/runner/gcloud.json
        gcloud auth activate-service-account --key-file=/home/runner/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}

    - name: 'Delete Nginx Deployment'
      run: |
        kubectl delete -f ejercicio-kubernetes/helm/nginx-deployment.yaml

    - name: 'Delete Nginx Service'
      run: |
        kubectl delete -f ejercicio-kubernetes/helm/nginx-service.yaml
